# 数组排序

In [1]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


## sort 函数

先看这个例子：

In [5]:
import numpy as np
names = np.array(['bob', 'sue', 'jan', 'ad'])
weights = np.array([20.8, 93.2, 53.4, 61.8])

np.sort(weights)

array([ 20.8,  53.4,  61.8,  93.2])

`sort` 返回的结果是从小到大排列的。

## argsort 函数

`argsort` 返回从小到大的排列在数组中的**索引位置：**

In [6]:
ordered_indices = np.argsort(weights)
ordered_indices

array([0, 2, 3, 1], dtype=int32)

可以用它来进行索引：

In [7]:
weights[ordered_indices]

array([ 20.8,  53.4,  61.8,  93.2])

In [8]:
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'],
      dtype='<U3')

使用函数并不会改变原来数组的值：

In [9]:
weights

array([ 20.8,  93.2,  53.4,  61.8])

## sort 和 argsort 方法

数组也支持方法操作：numpy的排序方法不会改变他的值

In [10]:
data = np.array([20.8,  93.2,  53.4,  61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int32)

`argsort` 方法与 `argsort` 函数的使用没什么区别，也不会改变数组的值。

In [14]:
data

array([ 20.8,  53.4,  61.8,  93.2])

但是 `sort`方法会改变数组的值：

In [12]:
data.sort()

In [13]:
data

array([ 20.8,  53.4,  61.8,  93.2])

数组的sort（）方法会改变他的值

## 二维数组排序

对于多维数组，sort方法默认沿着最后一维开始排序：

In [15]:
a =np.array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[ 0.2,  0.1,  0.5],
       [ 0.4,  0.8,  0.3],
       [ 0.9,  0.6,  0.7]])

对于二维数组，默认相当于对每一行进行排序：

In [18]:
np.sort(a)

array([[ 0.1,  0.2,  0.5],
       [ 0.3,  0.4,  0.8],
       [ 0.6,  0.7,  0.9]])

改变轴，对每一列进行排序：

In [19]:
np.sort(a, axis = 0)

array([[ 0.2,  0.1,  0.3],
       [ 0.4,  0.6,  0.5],
       [ 0.9,  0.8,  0.7]])

## searchsorted 函数

    searchsorted(sorted_array, values)

`searchsorted` 接受两个参数，其中，第一个必需是已排序的数组。

In [21]:
sorted_array = np.linspace(0,1,5)
values = np.array([.1,.8,.3,.12,.5,.25])

In [23]:
np.searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int32)

排序数组：

|0|1|2|3|4|
|-|-|-|-|-|
|0.0|0.25|0.5|0.75|1.0

数值：

|值|0.1|0.8|0.3|0.12|0.5|0.25|
|-|-|-|-|-|-|-|
|插入位置|1|4|2|1|2|1|

`searchsorted` 返回的值相当于保持第一个数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置：

例如 `0.1` 在 [0.0, 0.25) 之间，所以插入时应当放在第一个数组的索引 `1` 处，故第一个返回值为 `1`。

In [24]:

data = np.random.rand(100)
data.sort()

不加括号，默认是元组：

In [25]:
bounds = .4, .6
bounds

(0.4, 0.6)

返回这两个值对应的插入位置：

In [28]:
low_idx, high_idx = np.searchsorted(data, bounds)

利用插入位置，将数组中所有在这两个值之间的值提取出来：

In [29]:
data[low_idx:high_idx]

array([ 0.40443736,  0.42310099,  0.43789304,  0.44355839,  0.44964202,
        0.46617916,  0.47760479,  0.48780626,  0.48854001,  0.49760891,
        0.49790467,  0.51326612,  0.52135403,  0.53327523,  0.55342582,
        0.55507769,  0.5598168 ,  0.57879102,  0.58073305,  0.58828927,
        0.59015839,  0.59687066,  0.59698357,  0.59959044])