# 数组方法

In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## 求和

In [3]:
import numpy as np
a = np.array([[1,2,3], 
           [4,5,6]])

求所有元素的和：

In [4]:
sum(a)

21

指定求和的维度：

沿着第一维求和：

In [5]:
sum(a, axis=0)

array([5, 7, 9])

沿着第二维求和：

In [6]:
sum(a, axis=1)

array([ 6, 15])

沿着最后一维求和：

In [7]:
sum(a, axis=-1)

array([ 6, 15])

只有按行排序，没有按列排序吗
|

In [11]:
help(np.sum)

Help on function sum in module numpy.core.fromnumeric:

sum(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  I

或者使用 `sum` 方法：

In [8]:
a.sum()

21

In [9]:
a.sum(axis=0)

array([5, 7, 9])

In [10]:
a.sum(axis=-1)

array([ 6, 15])

## 求积

求所有元素的乘积：

In [12]:
a.prod()

720

或者使用函数形式：

In [13]:
prod(a, axis=0)

array([ 4, 10, 18])

## 求最大最小值

In [16]:
import numpy as np
a = np.random.rand(3, 4)
%precision 3
#数字精度
a

array([[ 0.385,  0.741,  0.249,  0.186],
       [ 0.283,  0.796,  0.18 ,  0.76 ],
       [ 0.015,  0.447,  0.7  ,  0.141]])

全局最小：

In [17]:
a.min()

0.015

沿着某个轴的最小：

In [18]:
a.min(axis=0)

array([ 0.015,  0.447,  0.18 ,  0.141])

全局最大：

In [19]:
a.max()

0.796

沿着某个轴的最大：

In [20]:
a.max(axis=-1)

array([ 0.741,  0.796,  0.7  ])

## 最大最小值的位置

使用 `argmin, argmax` 方法：

In [21]:
a.argmin()

8

In [22]:
a.argmin(axis=0)

array([2, 2, 1, 2], dtype=int32)

## 均值

可以使用 `mean` 方法：

In [23]:
a = np.array([[1,2,3],[4,5,6]])

In [24]:
a.mean()

3.500

In [25]:
a.mean(axis=-1)

array([ 2.,  5.])

也可以使用 `mean` 函数：

In [26]:
mean(a)

3.500

还可以使用 `average` 函数：

In [27]:
average(a, axis = 0)

array([ 2.5,  3.5,  4.5])

`average` 函数还支持加权平均：

In [28]:
average(a, axis = 0, weights=[1,2])

array([ 3.,  4.,  5.])

## 标准差

用 `std` 方法计算标准差：

In [29]:
a.std(axis=1)

array([ 0.816,  0.816])

用 `var` 方法计算方差：

In [30]:
a.var(axis=1)

array([ 0.667,  0.667])

或者使用函数：

In [31]:
var(a, axis=1)

array([ 0.667,  0.667])

In [32]:
std(a, axis=1)

array([ 0.816,  0.816])

## clip 方法

将数值限制在某个范围：

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

小于3的变成3，大于5的变成5。

## ptp 方法

计算最大值和最小值之差：

In [35]:
a.ptp(axis=1)

array([2, 2])

In [36]:
a.ptp()

5

## round 方法

近似，默认到整数：

In [37]:
a = np.array([1.35, 2.5, 1.5])

这里，.5的近似规则为近似到偶数值，可以参考：

https://en.wikipedia.org/wiki/Rounding#Round_half_to_odd

In [38]:
a.round()

array([ 1.,  2.,  2.])

近似到一位小数：

In [39]:
a.round(decimals=1)

array([ 1.4,  2.5,  1.5])